Submission form
dronetag/opendronelist pull request #20
Opened 2023-08-31 10:09 UTC by safrataxyz

A submission form for the opendronelist was implemented.

The things which are related to this PR
- Page for the form and two pages for the sucess and fail messages
- A lambda function which handles the form submission and creates an issue similar to this https://github.com/dronetag/opendronelist/issues/19 - this function will get extra configuration after the merge
- The html convertor was updated to include the pages, this was not tested, but it should be the same as the other files, will fix after merging when the workflow runs

2023-09-01 11:54 UTC, marianhlavac requested changes
Running the `html_convertor.py` script doesn't generate the form html files, I was unable to check the resulting form.

![Screenshot 2023-09-01 at 13 53 24](https://github.com/dronetag/opendronelist/assets/3010503/90b3123e-8f02-463d-ba35-c1e7ae5f22ca)

2023-09-01 12:59 UTC, safrataxyz commented
Please try again, I think I found out where the issue was and the generation succeeds every time now.

2023-09-01 13:28 UTC, marianhlavac requested changes
Looks great, but I'm missing the information that this will indeed create the GitHub issue. This should be told before sumitting the form, and after (we could display a link leading to GitHub issues). 

And we should not prefer this form, we should always prefer people to create the issue from their accounts, not anonymously via the form. So the first link should lead to GitHub issues, and add a text such as: "Don't have GitHub account? Use our submission form."

2023-09-04 20:36 UTC, marianhlavac approved these changes

2023-09-04 20:36 UTC, merged